name: Shuffly CI
on:
  pull_requests
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLORS: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - actions/checkout@v2
      - name Build
        run: cargo build --all-targets
      - name Run tests
        cargo test --all-targets
